version: "3"
services:
  database:
    image: timescale/timescaledb-ha:pg17
    restart: always
    privileged: true
    volumes:
      - pgdata:/home/postgres/pgdata/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: goods_db
    ports:
      - "5432:5432"

volumes:
  pgdata:
    external: true