version: "3"
services:
  database:
    image: timescale/timescaledb-ha:pg15-latest
    restart: always
    ports:
      - "6432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: goods_db